collectives/administration.py
collectives/api.py
collectives/event.py
collectives/forms.py
collectives/models.py
collectives/static/js/administration.js
collectives/templates/editevent.html
collectives/templates/event.html
collectives/templates/index.html
collectives/templates/user_roles.html

Ajout gestion des roles utilisateurs et des inscriptions
(UX tres sommaire et autorisations pas encore conformes au CdC)

Roles and registrations

---

collectives/models.py
collectives/templates/index.html

Ajout de la capacité de voir les places libres sur la page d'index

Liste: ajout de la vision des places restantes dans la sortie.

---

collectives/static/css/event/event.css

Arrondit les angles pour faire un design moins "dur"

Round corner for events in event list

---

collectives/event.py
collectives/models.py
collectives/templates/editevent.html
tests.py

Ajoute les champs manquants dans le formulaire des collectives et test la cohérence des paramètres

Expose online slots, registration times, + validation

---

collectives/event.py
collectives/forms.py
collectives/models.py
collectives/templates/event.html
tests.py

Fix pour la carte:
https://trello.com/c/jp5lL2Kv/102-statut-complet-dune-sortie

Distinguish has_free_slots and has_free_online_slots

---

collectives/administration.py
collectives/auth.py
collectives/event.py

Ça correspond à la tâche suivante
https://trello.com/c/BmyQPdzt/100-messages-derreur-en-fran%C3%A7ais

translate flash message in French.

---

collectives/api.py
collectives/forms.py
collectives/static/js/event/event.js
collectives/templates/event.html
tests.py

Autocompletion du nom d'utilisateur lors de l'inscription par un encadrant
Carte trello https://trello.com/c/LfN3FGIb/97-inscription-manuelle-dun-adh%C3%A9rent-par-un-encadrant-recherche-dynamique

Add autocomplete for registering users

---

collectives/static/js/event/edit.js
collectives/templates/editevent.html

Remove the period checkbox,
ask to set the end event' date,
copy start date whenever it is updated to the end date default value.
Default week start the Monday.

editevent: always set the end date.

---

collectives/event.py
collectives/helpers.py
collectives/views.py
config.py

Compare les dates en utilisant la timezone à définie dans le fichier config plutôt que celle du serveur 
Cf https://trello.com/c/nS6VpeQO/69-p%C3%A9riode-douverture-des-inscriptions-en-ligne

Enforce current time in correct timezone

---

collectives/event.py
collectives/models.py
collectives/static/css/event/edit.css
config.py

Ajout du template de description: https://trello.com/c/4eg77Zwv

Add default description template for event

---

collectives/static/css/main.css
collectives/templates/administration.html
collectives/templates/basicform.html
collectives/templates/editevent.html
collectives/templates/event.html
collectives/templates/index.html
collectives/templates/leader_profile.html
collectives/templates/macros.html
collectives/templates/profile.html
collectives/templates/user_roles.html
config.py

- remove now useless solidpanel css class, 
- remove now useless event macro, 
- remove a useless configuration parameter,
- add commentaries

Cleaning: remove some useless code

---

collectives/administration.py
collectives/static/caf/icon/activity.css
config.py

Rajout d'activity et modification de la mise à jour des actitivity types pour les forcer en db. https://trello.com/c/1FqpEKF8/111-types-dactivit%C3%A9-et-%C3%A9v%C3%A9nements

Add new activities and force them into database

---

collectives/auth.py
collectives/forms.py
collectives/static/css/main.css
collectives/templates/contact_link.html
collectives/templates/login.html

Pour l'instant email+license+date de naissance permettent de réinitialiser le compte/changer le mot de passe. Dans le futur une confirmation par email sera nécessaire, comme pour la création de compte.

Add account recovery page

---

collectives/utils/mail.py
config.py

https://trello.com/c/yNDYsh4l/94-mettre-un-place-un-syst%C3%A8me-denvoi-de-mails
La configuration a été positionnée sur demo.jnguiot.fr pour l'utiliser dès que c'est mergé
Pour l'utiliser:
` send_mail(subject="test", email="user@example.org", message="TEST")`

SMTP: add function to send a mail

---

collectives/static/css/event/event.css
collectives/static/js/event/eventlist.js

Change how click work in event list, and go to a more common way to handle click (using <a> tags)

Event list: Change click type to change location

---

collectives/forms/validators.py

Previous merge on form rework has broken the password modification due to missing library. Here is the fix.

Fix missing library

---

collectives/templates/profile.html

https://trello.com/c/68DJdbF7/149-nouvelle-proc%C3%A9dure-de-modification-de-ses-donn%C3%A9es-personnelles

Profile: Add new message for user update

---

collectives/administration.py
collectives/forms/__init__.py
collectives/forms/user.py
tests/test_auth.py

https://trello.com/c/ey5U98qW/146-pouvoir-manuellement-d%C3%A9sactiver-un-compte

Administrator: add enabled button for administrator + form refactor

---

collectives/event.py
collectives/models/event.py

Permet aux modérateurs d'éditer les collectives et inscrire/désinscrire les participants.
Note: les modérateurs sont les utilisateurs ayant les roles:
- Moderator
- Administrator
- President

Give more rights to Moderator and President

---

collectives/context_processor.py
collectives/models/user.py
collectives/static/css/main.css
collectives/templates/macros.html

Correspond à la carte:
https://trello.com/c/lvbVhdHe/132-tagger-les-adh%C3%A9rents-de-moins-de-25-ans-et-18-ans

Add tags for -18 and -25 license categories

---

collectives/static/js/event/eventlist.js

https://trello.com/c/i327gAZW/138-mettre-en-fran%C3%A7ais-la-pagination-de-la-liste-des-collectives
Traduction des paginations

Eventlist: translate pagination

---

collectives/api.py
collectives/auth.py
collectives/email_templates.py
collectives/event.py
collectives/models/user.py
collectives/utils/mail.py
config.py
tests.py

La meme PR avec les changements suggérés -- vu que la carte est déjà en testing je vais merger assez vite

Notification emails

---

collectives/static/css/event/event.css
collectives/static/js/event/eventlist.js
collectives/templates/index.html

https://trello.com/c/DmtogMSz/148-feedback-garder-en-session-le-filtre-sur-les-collectives

Event list: add persistence of filter, sort, and pagination

---

collectives/api.py
collectives/models/user.py

https://trello.com/c/ypOvmK9C/153-affichage-des-sorties-en-attente
- Je ne vois pas comment faire des tests pylint sur l'API pour s'assurer que ce qui est retourné. Mes tests manuels sont bons (anonyme, administrateur, user lambda, leader, superviseur), mais ça serait bien de les automatiser. Je suis preneur si quelqu'un peut m'aider à les mettre en place.
- Le filtre utilise grandement des any(). Ca rajoute encore des sous requètes à une requète qui en a beaucoup. J'espère que ce ne seera pas trop lent sur le site, mais seul les users spéciaux (leader, superviseur & co) déclenchent l'ajout de ces filtres. Ca devrait limiter la charge
- Après le merge de cette PR, il faudra diviser api.py en sous module, comme model et form

Event List: hide Pending activities only if necessary

---

collectives/static/js/event/event.js
collectives/templates/event.html

https://trello.com/c/VRBEoApb/154-message-fort-de-d%C3%A9sinscription

Event: change unregister message

---

requirements.txt

Fix de la version de werkzeug pour #98.

Workaround for #98

---

collectives/__init__.py
collectives/api.py
collectives/routes/administration.py
collectives/routes/auth.py
collectives/routes/event.py
collectives/routes/profile.py
collectives/routes/root.py
collectives/routes/views.py
collectives/templates/base.html
collectives/templates/event.html
collectives/templates/macros.html
collectives/templates/profile.html

Création d'un module pour les routes, séparation de `views.py` en deux blueprints `root` et `profile`. Pour l'instant `api.py` ne fait pas parti du module puisque ce ne sont pas vraiment des routes classiques, à voit si on veut l'intégrer

Routes module

---

README.md

N'hésitez pas à rajouter des éléments dans le README.md : ca fait un moment qu'on ne l'a pas mis à jour.

Doc: update README.md

---

collectives/api.py
collectives/static/css/administration.css
collectives/static/js/administration.js

https://trello.com/c/txDlMTls/144-ajouter-de-la-pagination-%C3%A0-la-liste-des-users
Ajout de la pagination, du filtrage et du classement.

Administration: add pagination to administration user list

---

collectives/api.py
collectives/static/js/event/eventlist.js

Retravail du filtrage des events pour le #109

Fix #109 by rework of event filtering

---

collectives/templates/base.html
config.py

C'est une petite modif pour afficher la version en cours d'utilisation dans l'IHM. C'est pratique pour vérifier si une version est bien déployée sur test.collectives.cafannecy.fr

Add version display in HMI

---

collectives/forms/event.py
collectives/models/event.py
collectives/routes/event.py
collectives/templates/editevent.html

* cast type and status to int
* slot numbers shall be positive integer
* set online slot to 0 by default
Fix #84
Event: use more wtforms-sqlalchemy to handle validation

events: define and use wtforms validators.

---

collectives/static/css/profile.css

trello: https://trello.com/c/68DJdbF7/149-nouvelle-proc%C3%A9dure-de-modification-de-ses-donn%C3%A9es-personnelles

Profile: Fix text size

---

collectives/forms/event.py

Pour compléter https://trello.com/c/opXbnFs0/141-import-des-collectives-%C3%A0-partir-des-fichiers-fournis-par-l%C3%A9quipe-de-la-revue suite à #117

Event remove placeholder from description

---

collectives/static/js/event/eventlist.js

Résolution du double chargement en ne lançant le chargement des données qu'après le changement de la page.

Event list: Fix #129

---

collectives/routes/event.py

Au lieu d'afficher une erreur si l'tulisateur est deja enregistré/rejeté, simplement repasse le statut à "Actif"
(Je conseille de regarder les changements en mode "Ignore whitespace change", le formatteur de VSCode a été un peu agressif)

Fix #120 -- re-registering a rejected user

---

.github/workflows/sphinx-build.yml

Ajout d'un test pour vérifier que la doc sphinx est buildable

Documentation: add test of sphinx build

---

.github/workflows/sphinx-build.yml
README.md
collectives/__init__.py
collectives/models/activitytype.py
collectives/models/auth.py
collectives/models/event.py
collectives/models/globals.py
collectives/models/registration.py
collectives/models/role.py
collectives/models/user.py
config.py
doc/source/collectives.rst
doc/source/howto.rst
doc/source/index.rst
doc/source/models.rst
doc/source/utils.rst

J'ai rajouté encore de la doc. Mon but est d'arriver à 100%, mais il reste un peu de travail. En voici déjà une partie supplémentaire qu'on peut intégrer.

Documentation: update document (no functionnal changes)

---

collectives/models/event.py
collectives/routes/event.py
collectives/static/css/event/edit.css
collectives/static/js/event/edit.js
collectives/templates/editevent.html

J'en ai profité pour nettoyer la fonction JS de validation des dates, et utiliser `moment` plutot. que `Date` pour parser les dates pour corriger #174

Address #159 Enforce registration closing before start of event

---

collectives/static/css/event/event.css
collectives/static/css/main.css
collectives/templates/event.html
collectives/templates/macros.html

Les icônes d'user actuelles dans les events étant assez moches (mal proportionnées, le nom fait nawak, etc...), je propose ça pour que ça rende mieux:

Event: better user icon

---

collectives/static/js/event/eventlist.js

Pagination: go to top of table when using pagination on index page.

---

collectives/static/css/main.css

Design: smaller panel title . Fix #138

---

collectives/templates/event.html

Rajout d'un bouton pour éviter de faire un copier coller pour envoyer des SMS ou des mails à une collectives.

Event: add a button to send a message to all participant (mail and SMS)

---

collectives/forms/__init__.py
collectives/forms/user.py
collectives/templates/base.html
collectives/templates/basicform.html
collectives/templates/editevent.html
collectives/templates/import_csv.html
config.py

display an alert if file selected is bigger thand the authorized server max size. Fix #178

File Upload: display an alert if selected  file is too big

---

collectives/static/css/event/event.css
collectives/templates/index.html

Suite à remarque de François, la liste des activités à filtrer se referme lorsque l'on sélectionne une valeur.

Event list: select for filter now closes when a value is selected.

---

collectives/utils/init.py
config.py

https://trello.com/c/RarBBywS/190-ajouter-lactivit%C3%A9-ski-de-fond-et-rando-nordique

Activity: merge ski nordique and ski de fond

---

collectives/forms/event.py
collectives/models/activitytype.py
collectives/models/event.py
collectives/models/user.py
collectives/routes/event.py
collectives/static/css/event/edit.css
collectives/templates/editevent.html

Rien de nouveau, juste la combinaison des deux revues précédentes rebasée sur master. Si tout est ok on pourra merger (peut être faire une MEP de la master actuelle avant?)

Single and multi activity workflow

---

collectives/api.py
collectives/email_templates.py
collectives/helpers.py
collectives/routes/event.py
collectives/utils/url.py

https://trello.com/c/vEpnEmuQ/200-url-rewriting-de-la-fiche-dune-collective

[FEATURE] Url rewriting of event to insert event title

---

collectives/routes/profile.py
collectives/templates/base.html
collectives/templates/legal_text.html

Suite à un retour des responsable d'activité, le terme "adhérent" semble plus approprié que "utilisateur"

[FIX] Fix wording and replace "utilisateur" by "adhérent"

---

collectives/routes/administration.py
collectives/static/js/administration.js
collectives/templates/administration.html
collectives/utils/misc.py
requirements.txt

https://trello.com/c/vwVgR0jc/183-export-sur-la-page-de-la-liste-des-comptes
Voilà, j'ai quasiment tout repris pour faire un export de role plutot qu'un export d'user.

[FEATURE] Administration: add XLSX export of roled users

---

.github/workflows/push_lint.yml
.github/workflows/push_test.yml
.github/workflows/sphinx-build.yml
collectives/api.py
collectives/forms/auth.py
collectives/routes/administration.py
collectives/routes/auth.py
requirements-tools.txt
requirements.txt

J'ai fait des modifications sur les requirements pour faire en sorte que les tests de pylint passe. Dès que la version patchée d'astroid sera diffusée sur Pypi, je reviendrais au pip de Pypi.
J'ai aussi séparé les outils des autres pip pour m'aider au déploiement.

Several actions on requirements.txt

---

collectives/routes/event.py
collectives/templates/event.html
collectives/utils/jinja.py
collectives/utils/misc.py

Depending on the user platform, there is no need to display the
'message' button. He won't be able to send an SMS.
fix #203

[FEATURE] do not give SMS access under desktop.

---

collectives/forms/auth.py
collectives/forms/event.py
collectives/routes/event.py
collectives/static/css/main.css
collectives/static/js/event/event.js
collectives/templates/auth/login.html
collectives/templates/auth/token_confirmation.html
collectives/templates/base.html
collectives/templates/basicform.html
collectives/templates/confidentiality_agreement.html
collectives/templates/contact_link.html
collectives/templates/editevent.html
collectives/templates/event.html
collectives/templates/import_csv.html
collectives/templates/legal.html
collectives/templates/legal_text.html
collectives/templates/print_event.html
collectives/utils/csv.py
config.py
tests.py

. redesign columns
. add robustness: check mandatory fields, value format

[FEATURE] Several enhancements in CSV import feature. Fix #123, #124, #125, #126, #127

---

collectives/__init__.py
collectives/static/caf/icon/activity.css
collectives/templates/editevent.html

and specify absolute path for activity icons.

[FIX] Fix #277: extract tail from scss compilation

---

collectives/__init__.py
collectives/static/css/event/edit.scss

[FIX] Fix #291: display a scrollbar in event description editor

---

collectives/models/user.py
tests.py

Je n'ai pas augmenté la taille du champ pour éviter les problèmes de mise à jour du schéma sur sqlite. Est-ce qu'on augmente quand même? Si oui, à combien?

[FIX] Fix #279: auto truncate too long string field

---

collectives/templates/administration.html

[FIX] admin page title is "Administration"

---

collectives/templates/base.html
collectives/utils/jinja.py
config.py

Un p'tit truc pour mieux lier les versions au github.

[FEATURE] Add github link on version tag

---

collectives/__init__.py
collectives/static/css/components/main-navigation.scss
collectives/static/css/legacy/main.scss

Mobile login tweaks

---

collectives/templates/partials/main-navigation.html

remove duplicate user profile link (now in right menu only)

---

collectives/static/css/all.scss
collectives/static/css/components/main-navigation.scss
collectives/static/css/legacy/event/event-details.scss
collectives/static/css/variables/_index.scss
collectives/static/css/variables/z-indices.scss

Use postion: sticky on main-navigation component

---

.gitignore
README.md
doc/source/howto.rst
run-test.py
run.py

• rename `run-test` to `run` (and remove original)
• update docs
• also adds WIP content to the tests instructions

[INTERNAL] rename `run-test.py` file and update docs

---

collectives/api/autocomplete_user.py
collectives/api/event.py
collectives/static/js/event/eventlist.js
collectives/templates/index.html

https://trello.com/c/Th2r2WYH/140-pouvoir-filtrer-la-liste-des-collectives-par-encadrant
Le filtrage par titre est cadeau

[FEATURE] add leader and title filtering on index list

---

.gitignore
collectives/__init__.py
collectives/routes/technician.py
collectives/templates/partials/main-navigation.html
collectives/templates/technician/logs.html
collectives/utils/error.py
config.py
logging.cfg

Vu que François demande souvent de jeter un coup d'oeil aux logs, voici un moyen de lui permettre de regarder les logs sans se connecter au serveur.
Ca pourra aussi nous être utile.
Le fichier de conifguration des logs sera aussi utile pour moi.

[FEATURE] Log viewer

---

collectives/routes/payment.py
collectives/templates/payment/payment_list.html

Carte trello: https://trello.com/c/hjnyq14U

[FEATURE] #332 XLSX export of event payments

---

collectives/api/payment.py
collectives/models/payment.py
collectives/routes/payment.py
collectives/static/css/legacy/administration.scss
collectives/static/css/payment-receipt.css
collectives/static/js/payment/my_payments.js
collectives/templates/payment/receipt.html

Permet à l'utilisateur d'imprimer un justificatif de paiement pour ses paiements en lignes sur la page "Mes paiements"

[FEATURE] Add option to print online payment receipts

---

collectives/routes/event.py
collectives/static/js/event/eventlist.js
collectives/templates/index.html

Demande de Romain pour pouvoir créer des liens vers les prochaines collectives d'une activité donnée

[FEATURE] Add an url endpoint to filter over a given activity type

---

collectives/templates/leader_profile.html
collectives/templates/profile.html

fix #325
Create a mailto: action on the user profile.

[FEATURE] create mailto link for contact email.

---

collectives/static/js/event/event.js
collectives/static/js/event/eventlist.js
collectives/static/js/trainees.js
collectives/static/js/utils/autocomplete.js
collectives/templates/event.html
collectives/templates/index.html
collectives/templates/trainees.html

Technical debt: single implementation for autocomplete stuff

Consolidate autocomplete

---

collectives/api/autocomplete_user.py
collectives/forms/event.py
collectives/static/js/utils/autocomplete.js
collectives/templates/editevent.html
collectives/templates/event.html

Dépend de #388 (consolidate autocomplete)

 [FEATURE] #170 Autocomplete for new leaders when editing events 

---

collectives/static/caf/icon/test.html
collectives/static/css/legacy/activity.scss
config.py

Ajout de l'activité _Randonnées lointaines_

[FEATURE] Add activity "randonnées lointaines"

---

collectives/static/css/components/_index.scss
collectives/static/css/components/pagination.scss
collectives/templates/administration.html
collectives/templates/base.html
collectives/templates/index.html
collectives/templates/leader_profile.html
collectives/templates/payment/payment_list.html
collectives/templates/profile.html
collectives/templates/profile/my_payments.html
collectives/templates/trainees.html

https://trello.com/c/OSuTiKd1
Mobile:
Desktop:

Update tabulator pagination

---

collectives/static/js/event/edit.js
collectives/templates/editevent.html
collectives/templates/import_csv.html

Nouveau MD editor.
Il pose moins de problème avec les smartphones et est mieux maintenu

[FIX] Fix #415 : Update MarkDown Editor to a newer fork

---

config.py

Ajout de l'activité _Via ferrata_

[FEATURE] Add activity "Via ferrata"

---

collectives/forms/user.py
collectives/models/role.py
collectives/routes/activity_supervison.py
collectives/routes/administration.py
collectives/routes/event.py
collectives/static/css/components/buttons.scss
collectives/static/css/components/menu-dropdown.scss
collectives/static/js/event/event.js
collectives/templates/partials/main-navigation.html
collectives/templates/trainees.html

Le club préfère maintenant parler d'encadrants bénévoles plutôt qu'initiateurs. En effet tous les encadrants ne sont pas forcément iniateur.

[FIX] Wording: Rename "Initiateur" to "Encadrant bénévole"

---

collectives/static/css/legacy/event/event-details.scss
collectives/templates/index.html

Minor tweaks to have a more readable index page on mobile

[FIX] Fix front page css for mobile

---

collectives/api/models.py
collectives/models/event_tag.py
collectives/static/js/profile.js
collectives/templates/administration.html
collectives/templates/base.html
collectives/templates/index.html
collectives/templates/leader_profile.html
collectives/templates/payment/list_all.html
collectives/templates/payment/payment_list.html
collectives/templates/profile.html
collectives/templates/profile/my_payments.html
collectives/templates/trainees.html

J'en ai profité pour mettre à jour tabulator, afin de mieux gérer la disposition des colonnes

Add filter to profile event list

---

collectives/api/admin.py
collectives/routes/activity_supervison.py
collectives/static/js/leaders_list.js
collectives/templates/leaders_list.html
collectives/templates/partials/main-navigation.html

On m'a soufflé que les superviseurs d'activités ne savaient pas qui étaient enregistrés comme encadrant dans leur activité. J'ai donc modifié l'interface des encadrants en formation pour afficher tous les encadrants.

[FEATURE] Display all leaders to activity supervisor (not only trainees)

---

collectives/api/admin.py
collectives/static/js/leaders_list.js

Better leader list display by grouping roles by leader.

[FIX] Better leader display

---

collectives/models/registration.py
collectives/routes/event.py
collectives/templates/event.html

Carte trello https://trello.com/c/6RPxZ6iC/245-pouvoir-sinscrire-%C3%A0-une-collective-alors-que-je-nai-pas-encore-renouvel%C3%A9-ma-licence
(Cette PR est intéressée, je viens de rencontrer ce problème)

Allow registration after license expires

---

collectives/routes/activity_supervison.py
collectives/routes/administration.py
collectives/routes/auth.py
collectives/routes/event.py
collectives/routes/payment.py
collectives/routes/profile.py
collectives/routes/root.py
collectives/routes/technician.py
collectives/templates/base.html
collectives/templates/event.html
collectives/templates/import_csv.html
collectives/templates/legal.html
collectives/templates/legal_text.html
collectives/templates/partials/event/payment_item_choice.html
collectives/templates/partials/main-footer.html
collectives/templates/partials/main-navigation.html
collectives/templates/payment/edit_prices.html

Petite amélioration: la variable `config`existe déjà, donc pas besoin de la redéclarer dans chaque `rendre_template`

[INTERNAL] use config variable in template instead of custom variable conf

---

collectives/utils/csv.py
config.py
tests.py

https://trello.com/c/43rsPKRi/248-gestion-des-%C3%A9coles-pour-indiquer-la-collective-m%C3%A8re-lors-dun-import

[FEATURE] Add event parent id in csv import

---

collectives/api/event.py
collectives/api/userevent.py
collectives/models/event.py
collectives/models/registration.py
collectives/routes/event.py
collectives/static/css/legacy/event/event-details.scss
collectives/static/js/event/event.js
collectives/static/js/event/eventlist.js
collectives/static/js/profile.js
collectives/templates/event.html
collectives/templates/index.html
collectives/templates/print_event.html
collectives/utils/jinja.py

J'ai rajouté une liste des présents pour la collective.
A noter que j'ai dû rajouté des types d'inscriptions... et c'est là ou on voit que le projet commence à avoir une bonne taille: ca touche beaucoup de chose. J'espère que je n'ai pas oublié un endroit.
https://trello.com/c/xWFCuNUB/121-absence-dun-inscrit
https://trello.com/c/hIfOkQmd/222-liste-des-absents-%C3%A0-une-sortie

[FEATURE] Add new registration status. Add attendance list.

---

collectives/routes/technician.py
collectives/templates/technician/logs.html

fix/368: Trier les logs serveurs par date décroissante

---

collectives/forms/payment.py
collectives/routes/payment.py
collectives/templates/payment/edit_prices.html

Address issue found when testing https://trello.com/b/tL1PNNZ0/caf-annecy-outils-informatiques?filter=label:Collectives

[FIX] Ensure uniqueness of payment item title

---

collectives/static/css/legacy/event/event-details.scss
collectives/static/js/event/eventlist.js

Cette PR ajoute deux petits changements que je voulais ajouter a https://github.com/Club-Alpin-Annecy/collectives/pull/477 , supprime un peu de css, et fait deux ajustements sur la liste des collectives (tabulator):
- Texte moins gros
- label "statut" après le titre de la collective et pas avant  (comme je l'avais deja changé sur la page de la collective)

a few small UI fixes

---

collectives/api/event.py
collectives/static/js/event/eventlist.js
collectives/templates/index.html

Une petite feature qu'on m'a demandé: pouvoir accéder directement à une date

[FEATURE] Add event filter by date

---

collectives/templates/event.html

Correction d'une faute d'orthographe + ajout de la notion de bénévole

[FIX] Payment typo for "encadrant" and "bénévole"

---

collectives/forms/event.py
collectives/forms/payment.py
collectives/models/event.py
collectives/models/payment.py
collectives/routes/event.py
collectives/routes/payment.py
collectives/static/js/event/edit.js
collectives/static/js/utils/autocomplete.js
collectives/templates/partials/event/payment_item_list.html
collectives/templates/payment/edit_prices.html

Ce système de copie des prix entre les events est fait pour aider les sorties qui ont tout le temps les mêmes prix, par exemple, le ski alpin et le canyoning. Ainsi, il peuvent facilement et rapidement recopier les prix d'un event à l'autre.

[FEATURE] Copy prices from another event

---

collectives/api/admin.py
collectives/forms/activity_type.py
collectives/forms/user.py
collectives/models/role.py
collectives/routes/activity_supervison.py
collectives/routes/administration.py
collectives/templates/leaders_list.html
collectives/utils/export.py

https://trello.com/c/hF3xlDU0/268-autoriser-les-responsables-dactivit%C3%A9-%C3%A0-g%C3%A9rer-leurs-encadrants

Gestion des leaders par les responsables d'activité

---

collectives/models/event.py
collectives/models/user.py
collectives/routes/event.py
requirements.txt

Rebasé les changements de @hug0be  en raison d'un conflit avec la waiting list, et adapté pour que la vérif ne s'applique qu'aux événements de type collectives et assimilés comme demandé par @fberu.

Fix/428 (#505 follow-up)

---

collectives/models/event.py
collectives/models/user.py
collectives/routes/auth.py
collectives/templates/base.html
collectives/templates/partials/event/self_register.html
collectives/templates/profile.html
collectives/utils/jinja.py
requirements.txt

https://trello.com/c/ZT5TZgR3/254-informer-ladh%C3%A9rent-que-son-num%C3%A9ro-de-t%C3%A9l%C3%A9phone-nest-pas-renseign%C3%A9

[FEATURE] Add warning to users with invalid phonenumbers

---

collectives/routes/profile.py

Génère une erreur si la signature n'est pas présente sur le serveur.

[FEATURE] check if president signature exist

---

collectives/routes/administration.py
collectives/utils/export.py

Fix typo correction

---

collectives/configuration.yaml
collectives/static/css/components/collectives-list.scss
collectives/templates/index.html
collectives/utils/jinja.py

https://trello.com/c/tKmDYfDi/257-bandeau-pour-communication-important
Voici un message modifiable directement dans la configuration du site par n'importe quel technicien:
A noter que par rapport à la demande, il y a quelques changements:
* Il aura une obligatoirement une description => DONE
* Optionnel, il pourra avoir une date et heure de début et de fin de publication. => Pas fait
* Il pourra avoir un statut: publié ou dépublié => Il n'y a pas de statut. C'est juste que si le message à est vide, c'est pas affiché
* comme une seule et unique information pourra être affichée, ce sera tjs la plus récente et en statut publiée qui sera affichée
* Une information peut être modifiée et supprimée
Seul un administrateur peut créer / modifier / supprimer un bandeau information => C'est …

[FEATURE] add a banner message

---

collectives/models/configuration.py
collectives/routes/technician.py
collectives/templates/technician/configuration.html
config.py

On a parlé, voici le mécanisme de cache de la conf.
C'est thread safe sur le même serveur. Si un jour on a deux serveurs, le rechargement sera fait en 1 minutes max.

[FEATURE] Add cache to configuration in DB

---

README.md

Bonjour tout le monde, j'ai eu Romain au téléphone aujourd'hui pour me présenter le topo, je viens d'installer le projet et j'ai dû bidouiller un peu pour faire tourner le site car il manquait la db en suivant pas à pas le README, donc je me suis dit que c'était une bonne première contribution ? :slightly_smiling_face:

Updated docs to include setting up local database

---

collectives/routes/auth.py
collectives/templates/auth/activate_recover.html
collectives/templates/auth/login.html

Cf #541, guide les utilisateurs vers la page de récupération si ils ont changé de licence

More explicit account recovery messages

---

collectives/routes/auth.py

Mise à jour suite à la demande de @fberu

[FEATURE] Better message in case of wrong phone number

---

collectives/routes/event.py
collectives/templates/event/event.html
collectives/utils/export.py

@fberu, peux tu me confirmer que le fichier te convient ?

[FEATURE] Export list of registrants for a collective

---

collectives/models/upload.py

Avoid cropping useful info for non-landscape images

[FIX] Fit rather than crop uploaded images

---

.vscode/settings.json
collectives/api/event.py
collectives/forms/event.py
collectives/forms/user_group.py
collectives/models/event/misc.py
collectives/models/event/model.py
collectives/models/event/registration.py
collectives/models/user_group.py
collectives/routes/event.py
collectives/static/css/legacy/event/edit.scss
collectives/static/js/user-group-form.js
collectives/static/js/utils/autocomplete.js
collectives/templates/event/editevent.html
collectives/templates/event/event.html
collectives/templates/partials/user-group-form.html
collectives/templates/partials/user-group-text.html
collectives/utils/payment.py
migrations/versions/1006bccb75da_fix_group_event_fk.py

Partie 2 de l'ajout de conditions plus flexible: édition des restrictions dans le formulaire de création/édition d 'événements.
La partie 3 concernera la même chose, mais pour les tarifs. Là ça fait déjà une bonne PR :)

Event user restrictions UI

---

collectives/forms/payment.py
collectives/forms/user_group.py
collectives/models/event/misc.py
collectives/models/event/model.py
collectives/models/event/registration.py
collectives/models/payment.py
collectives/routes/payment.py
collectives/static/css/legacy/payment/edit-prices.scss
collectives/static/js/user-group-form.js
collectives/static/js/utils/autocomplete.js
collectives/templates/activity_supervision/leaders_list.html
collectives/templates/event/event.html
collectives/templates/partials/event/payment_item_list.html
collectives/templates/partials/user-group-form.html
collectives/templates/partials/user-group-text.html
collectives/templates/payment/edit_prices.html
collectives/templates/reservation/new_rental.html
collectives/templates/reservation/reservation.html
collectives/templates/reservation/reservationLine_completed.html
collectives/templates/reservation/reservationLine_ongoing.html
collectives/templates/reservation/reservationLine_planned.html
tests/fixtures/payment.py
tests/test_payments.py

Partie 3/3 des restrictions d'inscription
Forms pour éditer les restrictions des tarifs
https://trello.com/c/GFR3eItq/263-tarif-r%C3%A9serv%C3%A9-aux-encadrants

[FEATURE] UI for editing price restrictions

---

collectives/__init__.py
collectives/email_templates.py
collectives/forms/auth.py
collectives/forms/user_group.py
collectives/models/activity_type.py
collectives/models/event/event_type.py
collectives/models/utils.py
collectives/routes/auth.py
collectives/routes/event.py
requirements-tools.txt
requirements.txt
tests/events/test_event.py

- FLASK_ENV, config['ENV'] removed -> use DEBUG instead
- import Markup, espace from markusafe
- Move to recent astroid

[INTERNAL] Update for compat with flask 2.3 / new pylint

---

collectives/api/admin.py
collectives/forms/user.py
collectives/models/user/model.py
collectives/routes/administration.py
collectives/routes/profile.py
collectives/static/js/administration.js
collectives/templates/profile.html
collectives/templates/profile/delete_user.html
tests/test_profile.py

Ajoute une page pour anonymiser un compte utilisateur (les données personnelles sont supprimées, mais on garde les registrations etc pour les stats)

[FEATURE] Delete (anonymise) user accounts

---

.github/workflows/build_docker.yml
Dockerfile
deployment/docker/entrypoint.sh
deployment/docker/logging.cfg
deployment/k8s/.gitignore
deployment/k8s/collectives.example.yaml
doc/source/deployment.rst
doc/source/docker.rst
doc/source/howto.rst
doc/source/index.rst

Une déclinaison Docker et kubernetes du déploiement

[INTERNAL] Setup new deployment : docker and kube

---

collectives/models/event/payment.py
tests/unit/test_event.py

Fix typo in function name + add unit test

Fix paying event waiting list update

---

collectives/api/event.py
collectives/routes/event.py

Fix a couple HTTP 500 errors seen in logs

[FIX] Make event list more robust to bad params

---

collectives/templates/event/event.html

[FIX] Fix #699 : display when registrations will open if it is not

---

collectives/api/models.py
collectives/models/role.py
collectives/static/css/legacy/main.scss
collectives/templates/partials/form-fields.html
collectives/templates/user_roles.html

Pour aider les admins, j'ai ajouté une description des rôles et refait un peu l'interface

[FEATURE] Better roles management interface for admin

---

collectives/static/css/components/collectives-list.scss
collectives/static/js/event/eventlist-filters.component.js
collectives/templates/index.html

Display Activity, type, and tags icon in filters and tag

feat(event-list): display icons in filters

---

collectives/static/css/components/collectives-list.scss
collectives/static/js/event/eventlist-filters.component.js
collectives/templates/index.html

feat: add unselect button

---

collectives/models/event/__init__.py
collectives/models/event/registration.py
collectives/models/registration.py
collectives/routes/event.py
tests/unit/test_registrations.py

Make race conditions checks more easily testable

Check for duplicate registration that may arise due to race conditions

---

collectives/routes/administration.py
collectives/routes/auth/signup.py
collectives/routes/auth/utils.py
collectives/utils/extranet.py
collectives/utils/time.py
tests/auth/test_local_signup.py

Fix account recover not updating existing user license

---

collectives/utils/crawlers.py
tests/events/test_event.py

+ single cached regex for better perf

Fix crawler test err 500 on `None` user agents

---

collectives/static/css/components/collectives-list.scss
collectives/static/js/api.js
collectives/static/js/event/eventlist-filters.component.js
collectives/static/js/event/eventlist.component.js
collectives/templates/index.html

Make mulltiselect filters less likely to be displayed _above_ the component:
- use appendTo="self"
- remove filter box / selectAll and reduce padding to decrease vertical height

Fix display of filter multiselect (prevent overflowing top of viewport)

---

collectives/api/admin.py
collectives/forms/activity_type.py
collectives/forms/stats.py
collectives/forms/upload.py
collectives/forms/user.py
collectives/models/activity_type.py
collectives/models/badge.py
collectives/models/event/event_type.py
collectives/models/role.py
collectives/models/utils.py
collectives/routes/activity_supervison.py
collectives/routes/administration.py
collectives/static/js/activity_supervision/badges_list.js
collectives/static/js/activity_supervision/leaders_list.js
collectives/templates/activity_supervision/badges_list.html
collectives/templates/activity_supervision/leaders_list.html
collectives/templates/user_badge_renew.html
collectives/utils/badges.py

- fix volunteer list showing all badges
- fix leader list not show organizer
- enum-based filter headers
- fix user badge creaation/renewal form

Fix supervision leader and badge lists

---

collectives/routes/event.py
collectives/static/css/print-event.css
collectives/templates/event/print_event.html
tests/events/test_event.py

[FEATURE] Better collective sheet, with html and resized logo. Accept images

---

collectives/forms/auth.py
collectives/forms/user.py
collectives/static/css/components/login-form.scss
collectives/templates/partials/form-fields.html

Offre la possibilité d'afficher le mot de passe ![image](https://github.com/user-attachments/assets/a4d14ecb-30b4-4668-bf95-d256748f19eb)

[FEATURE] Add password reveal on selected password fields

---

collectives/api/event.py
collectives/configuration.yaml
collectives/routes/event.py
collectives/templates/event/editevent.html
collectives/templates/event/preview.html
tests/events/test_event.py

Limit event visibility for unauthenticated users to a month.

[SECURITY] Do not allow browsing from unauthorized user agent. 

---

collectives/configuration.yaml
collectives/email_templates.py
collectives/routes/auth/signup.py
collectives/routes/event.py
collectives/static/css/legacy/event/event-details.scss
collectives/static/js/event/event.js
collectives/templates/event/partials/admin.html
collectives/templates/partials/event/self_unregister.html
tests/auth/test_local_signup.py
tests/events/test_event.py
tests/events/test_registrations.py
tests/fixtures/user.py
tests/mock/extranet.py
tests/mock/mail.py
tests/test_extranet.py

- Add optional "reason" field to rejection/unregistration emails 
- Send email when waiting list registration is manually confirmed
- Utility for testing mails being sent

[FEATURE] Improve registration update mails

---

collectives/api/event.py
collectives/forms/event.py
collectives/models/event/model.py
collectives/models/event/registration.py
collectives/models/event/role.py
collectives/routes/event.py
collectives/static/js/event/edit.js
collectives/templates/event/editevent.html
collectives/templates/event/partials/admin.html
migrations/versions/9590becba403_add_include_leaders_in_count.py
tests/unit/test_event.py

A few features requested by activity supervisors:
- Allow leaders to removed themselves from events (if not main leader)
- Better synchronization between date pickers, visualize constraints
- Available slot fields close to each other
- Option to include leader count in slot count
- Option to sort attendance table by name
- Add list of leader mails

Event management improvements

---

collectives/models/event/role.py
collectives/routes/event.py
collectives/templates/event/editevent.html
collectives/templates/event/partials/admin.html

- Fix self-removing as a leader from an event
- Clarify form label
- More options for sorting attendance table

Fixes for event management

---

collectives/static/caf/icon/handicaf.svg
config.py

Demandé par le CAF de Sallanches
Sera désactivé sur le site d'Annecy

[FEATURE] Add HandiCaf as activity
