collectives/event.py
collectives/forms.py
collectives/models.py

Affiche seulement les activités que l'utilisateur peut encadrer
Carte trello https://trello.com/c/Ir9TZkdu/95-cr%C3%A9ation-collective-nafficher-que-les-activit%C3%A9s-quun-encadrant-ne-peut-encadrer

Restrict activity choices in event management

---

collectives/api.py
collectives/event.py
collectives/models.py
collectives/static/caf/icon/activity.css
collectives/static/css/event/event.css
collectives/static/js/event/eventlist.js
collectives/static/js/profile.js
collectives/templates/index.html
collectives/templates/leader_profile.html
collectives/templates/profile.html
collectives/views.py

A first step into a different event list page. Using tabulator adds us a great deal of standard function (infinite scroll, pagination, filtering, sorting, grouping, etc...). Plus it uses the api.
In this PR, I have:
- integrated tabulator,
- added pagination, https://trello.com/c/b7TE87Qn/14-paginer-la-liste-des-collectives
- grouped event by start date
- displayed leader name into list https://trello.com/c/pMW1Cmvg/103-liste-des-collectives-afficher-le-nom-de-lencadrant
In next PR:
- a better design around tabulator
- integrate filtering and sorting by activity or date https://trello.com/c/lbbvhrSs/25-pouvoir-trier-et-filtrer-la-liste-de-collectives

Event list: avec tabulator

---

collectives/context_processor.py
collectives/static/js/event/eventlist.js
collectives/static/js/profile.js
collectives/templates/base.html
collectives/templates/index.html

Utilise l'heure serveur plutot que moment.js pour les comparaisons de date (utile si le browser est dans une autre timezone, ce qui est fréquemment mon cas par exemple)

Use app timezone rather than client for time comparisons

---

collectives/auth.py
collectives/templates/profile.html
collectives/views.py

https://trello.com/c/ToVw6f0r/128-profil-utilisateur-ne-pas-rendre-modifiable-les-donn%C3%A9es-venant-de-lextranet
Mettre à dispo un bouton sur le profil utilisateur permettant de resynchroniser les données suite au changement côté extranet

Add explicit extranet sync button

---

collectives/models/event.py
collectives/templates/editevent.html
tests.py

J'ai conservé le champ, car il est chiant à enlevé dans sqlite. Mais ca sera à faire plus tard.
https://trello.com/c/yXuK7Vj4/107-supprimer-le-champ-d%C3%A9nivel%C3%A9-difficult%C3%A9-cotation

Event: remove short description

---

collectives/models/event.py
collectives/routes/event.py
collectives/static/css/administration.css
collectives/static/css/event/edit.css
collectives/static/css/event/event.css
collectives/static/js/event/edit.js
collectives/templates/editevent.html
collectives/templates/import_csv.html
collectives/utils/csv.py
collectives/utils/export.py
config.py
requirements.txt

Prototype de remplacement de Quill par un éditeur markdown "semi-WYSIWYG"
+ ajout de lien automatique sur les URL
Les avantages sont un format de texte beaucoup plus lisible, facile à manipuler et à corriger en cas de fausse manip, ainsi qu'un plus large support Python

Markdown editor

---

collectives/static/js/event/edit.js
collectives/templates/editevent.html

Ajout de la validation des dates:
https://trello.com/c/eoxmtzRm/99-cr%C3%A9ation-collective-validation-des-champs-de-type-date
- vérification qu'il s'agit d'une vraie Date
- la fin des inscriptions par internet doivent être antérieures à la date de début de la collective
- les dates de fin doivent être postérieures aux dates de début
- les dates d'inscriptions par internet ne peuvent plus être remplies à moitié

Event: add date validation during event management

---

collectives/api.py
collectives/static/js/event/eventlist.js

Always use current server date for "end" filter
Compatible with existing persistent filters

Use server data in "end" filter

---

collectives/utils/mail.py
config.py
requirements.txt

Conformément aux tests de mail tester, il manquait des headers:
- Message-id
- Date
- DKIM-Signature
A noter que la signature DKIM est désactivée s'il n'y a pas les paramètres DKIM_KEY et DKIM_SIGNATURE dans la configuration.

Mail: add Date and message ID field. Add DKIM. Should fix #135

---

collectives/models/event.py
collectives/utils/render_markdown.py
doc/source/utils.rst

- Extract markdown rendering from `model.event` to `utils.render_markdown`
- Fix unintuitive markdown behaviour: Standard markdown requires a blank line before the start of  each list, but Github-flavoured markdown does not, nor does SimpleMDE editor preview. This can be confusing for users. To fix that add a blank line before the first item of each list.
For instance, this will fix the "Required gear" list in https://test.collectives.cafannecy.fr/event/17

Markdown rendering cleanup and fix

---

collectives/templates/editevent.html

For old people who don't take time to read warnings, display a more explicit message for maximum authorized image size

More explicit message for maximum authorized image size

---

collectives/forms/user.py

Certains de nos utilisateurs ne savent pas ce qu'est un "avatar". Remplacement du terme avatar par "photo de profil"

Wording: replace "avatar" by "photo de profil"

---

CODING.md

Je propose qu'on se mette à rajouter des tags lorsque l'on merge des commits dans master, et qu'on le fasse tout le temps en "squash". Ca permettra de générer une release note facilement. Qu'en penses tu Gilles? Le plus important est de rajouter le tag au moment du merge dans github.

[INTERNAL] Update CODING rules with commit tags

---

collectives/context_processor.py
collectives/static/js/event/eventlist.js
collectives/templates/editevent.html
tests.py

Des encadrants "se plaignent" ou disent qu'indiquer une heure de début et de fin sur une collective n'est pas opportun. D'autres disent que oui. Ceux qui "se plaignent" mettent du coup des heures bidons genre 1h du mat pour tenter de faire comprendre au participant qu'il faut bien lire la description de la sortie et notamment l'heure de rendez-vous. 
Afin de satisfaire tout le monde, si l'encadrant met "0h00" comme heures de début et fin, les heures ne s'affichent pas dans le titre de la collective

[FEATURE] Do not display time in event title when set to midnight

---

tests.py

The `TestImportCSV` unit test was overloading the `create_app` from `ModelTest`, thus removing the part that sets the SqlAlchemy URI to a temporary db, and causing havok on the usual database

[INTERNAL] Fix unit test overriding db

---

collectives/utils/render_markdown.py

- Restrict autolink to http+https 
- Fix links with implied protocol (like www.domain.com)

Fix #266 markdown auto links

---

collectives/templates/administration.html
collectives/templates/index.html
collectives/templates/leader_profile.html

I found [an existing bug on mobile in the `tabulator` library](https://github.com/olifolkerd/tabulator/issues/2506#issuecomment-562960566) which affected the version we were using. So I'm upgrading the library.
To avoid incompatibility with any of the backend components, I'm being conservative and only upgrading to the latest `4.5.x` minor version: `4.5.3`.

Conservatively upgrade tabulator to 4.5.3

---

collectives/static/js/event/eventlist.js

This `console.log` was added for debugging [when working on a bug fix](https://github.com/Club-Alpin-Annecy/collectives/pull/195/files#diff-46e11f9d467777f47473d75e1e728e6cR246), but left there. I'm removing it to avoid cluttering the js console

[FIXED] Remove unneeded console.log that was added for debugging

---

collectives/__init__.py
requirements.txt

@jnguiot was having a lot of issues with sass compilation on Windows, so switching to a more portable libsass implementation should make things much better

Use libsass instead of pyScss

---

collectives/utils/extranet.py

`strptime` lève une exception pour la date '0000-00-00' qui est retournée pour les licences expirées (l'an 0 n'existe pas)

[FIX] Fix #295 error 500 for expired licenses

---

.github/workflows/sphinx-build.yml
README.md

Rename the sphinx github workflow to Doc. Sphinx is a technology, not a
product.
Add the Doc badge in the README

[INTERNAL] add the sphinx badge in the README

---

collectives/static/js/administration.js
collectives/static/js/event/eventlist.js

The tabulator-paginator class only defines first, last, next and previous buttons. We need also to tweak the tabulator-pages classe.
I were not able to "disable" the active page, but that was not requested…
Fix #288

[FIX] eventlist: scroll to top when using pagination. 

---

.github/workflows/push_lint.yml
.github/workflows/push_test.yml
.github/workflows/sphinx-build.yml

original workflow names reflected the trigger ("push_" prefix). Not
valid but not really needed to rename anyway..

[INTERNAL] workflows: trigger in push and pull requests.

---

collectives/routes/auth.py

Sera mergé après la résolution de #328 , mais vous pouvez déjà faire la revue.

[FIX] Fix #326. Display error if user has no email in FFCAM user info.

---

collectives/__init__.py

Ca sera toujours un peu lent sur des environnements de non production, mais sinon, on repasse à moins de 100ms pour générer la page.

[FIX] Fix #348: accelerate webpage generation for production

---

collectives/utils/mail.py
config.py

Différencier le login SMTP de l'adresse d'émission afin d'utiliser des providers de mail type Mailjet

Differentiate SMTP login and SMTP sender address

---

collectives/__init__.py

Corrige les erreurs liées à la migration des trigrammes:
de facon plus générale n'initialise plus le compte administrateur/activités lorsqu'on lange une commande de migration comme `flask db upgrade`

Do not populate db when running migrations. Avoids truncation error

---

cli_test_payline.py
collectives/routes/payment.py
collectives/utils/misc.py
collectives/utils/payline.py
collectives/utils/url.py
requirements.txt

Le but de cette PR est de stocker plus d'infos relatives au paiement  (quelle collective, date, encadrants etc) coté Payline, afin de permettre de retrouver à quoi correspondent les paiements si on a un crash BD. 
Pour  cela on remplit les champ "privateDataList", qui est un "faux" dictionnaire (une liste de paires "key" + "value"). La dernière version Pip de PySImpleSoap (qui date de 2014) ne supportait pas ce type de données, je l'ai remplacé par une version Github plus récente.

Store payment metadata in Payline

---

collectives/static/js/event/eventlist.js

Beaucoup de retours indiquant que l'affichage de 10 collectives est trop peu et que la pagination est "complexe".
Je propose de mettre d'aficher 25 collectives par défaut. Je ne pense pas que cela impactera les performances d'affchage

[FIX] Display 25 events by default

---

requirements.txt

On a des erreurs suite au package dateutil qui n'est plus installé par défaut. On le force donc dans les requirements

[FIX] Add required dateutil package

---

collectives/models/registration.py
collectives/routes/event.py
collectives/templates/event.html

Quelques modifs mineures:
- Gestion plus précise des transition de statut d'inscription (c.f. RegistrationStatus::transition_table())
- Vérification côté serveur que tout est ok
- Suppression uniquement possible pour les statuts Refusé et Désinscrit (comme ca on est sur que l'utilisateur soit au courant, i.e., ait recu un mail ou fait lui même l'action)
- Suppression de la liste des inscrits en attente de renouvellement en doublon 
- Suppression de la route "reject_registration" qui était encore utilisée pour les inscriptions en attente de renouvellement

Fine-tune registration status transitions, enforce on server side

---

collectives/models/user.py

fix/376: [Robustesse] Vérifier si la date d'expiration de la licence n'est pas null

---

collectives/routes/payment.py

Quelques améliorations / corrections sur l'export des paiements:
* Ajout du type d'événement
* Suppression d'un "forçage" en string de tous les champs afin d'exporter un paiement en float + ajout de la monnaie €
* Suppression de la colonne "Date de remboursement": fonctionnalité non supportée prêtant à confusion: les gens pensent qu'une fois le remboursement réalisé sur Monext la date apparaissait automatiquement sur le site des collectives
* Redimensionnement de certaines colonnes

[FIX] Fix #487 and #507: export payments

---

collectives/templates/leader_profile.html

Affichage de l'entête "Sorties encadrées passées" au lieu de "Sorties encadrées effectuées" car certaines sorties peuvent être annulées

[FIX] Fix #311: Wording - replace "done" by "past" in leader events list

---

collectives/models/event.py
collectives/routes/event.py
collectives/templates/editevent.html
collectives/templates/event.html

Regarding @fberu remark on https://github.com/Club-Alpin-Annecy/collectives/pull/497#issuecomment-1079929247
> être averti par mail est top. Malheureusement les encadrants ont constaté que des gens s'auto désinscrivent le soir pour le lendemain (des fois à 2h du mat pour un départ à 7h). Dans ce cas là, celui sur liste d'attente est prévenu tardivement qu'il est inscrit et a de grandes chances de ne pas voir la notification. Et du coup l'encadrant grognera le matin au parking parce qu'il n'est pas là
Now, wainting users are automatically updated to subscribed users only if registration time slot is still. After that, subscribing has to be done manually by leader.
Plus, I have fix a 500 error if registration time wasn't set.

Fix and improvement of waiting list

---

requirements-tools.txt

La version pylintrc la plus récente (2.15) amène beaucoup de nouvelle norme. Si on veut se mettre en conformité, il faut qu'on passe du temps dessus. En attendant, je pin la version pour pouvoir merger

[INTERNAL] Pin pylint version.

---

collectives/configuration.yaml
collectives/utils/init.py
collectives/utils/payline.py
config.py

Depuis la mise en place de configuration dans la DB, payline ne fonctionne plus car le chemin vers le wsdl n'est pas le bon. Il n'est vraiment utile de changer le chemin du WSSDL dans l'interface, je la supprime donc.

[FIX] Add configuration obsolete management. Remove payline WSDL from db configuration

---

collectives/routes/administration.py
collectives/routes/auth.py
collectives/routes/profile.py
collectives/utils/extranet.py
collectives/utils/payline.py

- Supprime les erreur 500 lors des erreurs extranet: log l'erreur et affiche un message non spécifique à l'utilisateur
- (Plus important) Corrige les paramètres Payline suite au passage en snake_case
A la base je voulais passer tout Payline sous zeep, mais il y'a une parse erreur sur un message de retour... je reverrai ça plus tard

Soap fixes

---

collectives/templates/index.html

Il s'avère que la résolution était sous dimensionné (eg: pour une taille d'écran de 1000, on proposait une image de 900).
C'est corrigé

[FIX] Better resolution for cover

---

.github/workflows/db_migrations.yml

Fix github test: mariadb 10.5 is not available on jammy. Bump to 10.8

[INTERNAL] Fix db migration tests

---

.vscode/settings.json
collectives/forms/payment.py
collectives/models/__init__.py
collectives/models/event/misc.py
collectives/models/event/model.py
collectives/models/event/payment.py
collectives/models/event/registration.py
collectives/models/payment.py
collectives/models/user/misc.py
collectives/models/user_group.py
collectives/routes/event.py
collectives/routes/payment.py
collectives/templates/event/event.html
collectives/templates/partials/event/payment_item_list.html
collectives/templates/payment/edit_prices.html
collectives/utils/csv.py
doc/source/models.rst
doc/source/user_group.rst
migrations/versions/604ff8589a3a_add_user_groups.py
pylintrc
tests/events/test_event.py
tests/fixtures/event.py
tests/fixtures/payment.py
tests/unit/test_event.py
tests/unit/test_roles.py
tests/unit/test_user_group.py
tests/unit/utils/test_autocomplete.py
tests/unit/utils/test_import_csv.py

Pas mal de tickets visent à avoir des restrictions plus avancées pour les events et tarifs.
Cette PR vise à préparer les bases pour cela en remplacant les restrictions actuelles (parent_event, is_leader, etc) par le concept de "groupe d'utilisateur" défini par des règles dynamiques (inscription à un ou plusieurs événements, role, licence, etc)
Pour l'instant ces nouvelles fonctionnalités ne sont pas exposées; l'interface reste exactement la même. En revanche, le code migre de l'ancienne représentation (parent_event, is_leader) vers la nouvelle basée sur les groupes. 
Cette migration n'est pas faite au niveau de Flask-Migrate (cela serait fragile si les modèles changent avant que la migration ne soit effectuée), mais au fur et à mesure:
- tous les nouveaux éléments utilisent la nouvelle …

[INTERNAL] Refactor event and price restrictions

---

collectives/api/event.py
collectives/static/js/event/eventlist.js

Fix cette issue: [Issue 604](https://github.com/Club-Alpin-Annecy/collectives/issues/604)
**NB: les règles implémentées sont:**
1. Le badge "liste d'attente" s'affiche si:
- Si aucun slot online n'est dispo mais qu'il y a des slots sur waiting_list
- si plus de slots dispo mais qu'il reste des slots en waiting_list
2. Le badge "liste d'attente" ne s'affiche pas" si:
- il reste des slots online dispos (même s'il y a des slots sur waiting_list)

FIX-Issue-604-Waiting_list_badge

---

collectives/static/js/event/eventlist.js

https://trello.com/c/VxhjzM7X/284-garder-tous-les-filtres-de-la-liste-d%C3%A9v%C3%A9nement-en-m%C3%A9moire
En gros des utilisateurs se plaignaient que lorsqu'ils revenaient à la liste des collectives, certains filtres étaient perdus. En revanche ça n'aurait pas de sens de persister le filtre de date (par ex.) sur du long terme, du coup maintenant les filtres sont gardés tant que la session du navigateur est ouverte ET que la page a été rechargée depuis moins d'un jour 
@jnguiot du coup j'ai changé le "start" en "end" comme dans ta PR, c'est cassé pour l'instant en attendant que #634 soit mergée

[FEATURE] Preserve data, title, leader filter for duration of session

---

collectives/utils/export.py
tests/events/test_event.py

[ADD] Split de la colonne "Nom" de l'export des participants d'une collective en "Prénom" et "Nom" (uppercase)

---

collectives/routes/event.py
collectives/templates/event/editevent.html
collectives/templates/partials/event/self_register.html
tests/events/test_registrations.py
tests/fixtures/client.py
tests/fixtures/event.py

Petite modif du workflow des désinscriptions: une désinscription de la liste d'attente ne bloque plus les inscriptions à une autre collective.
J'en ai profité pour rajouter des tests

[FIX] Unregister from waiting list should not block registering on other events

---

collectives/configuration.yaml
collectives/email_templates.py
collectives/models/event/payment.py
collectives/models/user/misc.py
collectives/models/user/role.py
collectives/routes/event.py
collectives/templates/partials/event/self_register.html
tests/fixtures/app.py
tests/unit/test_event.py

- Skip users that have an active registration to another event
- Skip users that would not be able to pay for the event
- Delete other waiting registrations for simultaneous events

Fix waiting list updates for simultaneous registrations

---

collectives/api/event.py

Ajout d'un CORS pour permettre au site vitrine de récupérer la liste des collectives en js

[INTERNAL] Add CORS to allow external site to request event list in js

---

collectives/static/js/question/show_answers.js

Les réponses longues au questionnaire sont tronquées par tabulator. Je fais sauter ça :)

[FIX] Fix truncated long answer in answer table

---

collectives/api/autocomplete_user.py
collectives/forms/event.py
collectives/forms/user.py
collectives/models/__init__.py
collectives/models/activity_type.py
collectives/models/badge.py
collectives/models/event/__init__.py
collectives/models/event/event_type.py
collectives/models/event/misc.py
collectives/models/event/role.py
collectives/models/role.py
collectives/models/user/badge.py
collectives/models/user/role.py
collectives/routes/activity_supervison.py
collectives/routes/event.py
collectives/static/js/activity_supervision/badges_list.js
collectives/templates/activity_supervision/activity_supervision.html
collectives/templates/activity_supervision/badges_list.html
collectives/templates/activity_supervision/leaders_list.html
collectives/templates/event/editevent.html
collectives/templates/event/event.html
collectives/templates/event/partials/admin.html
collectives/templates/profile.html
tests/unit/test_roles.py

Ajoute le rôle "Organisateur (activité)", qui permet de créer des événements d'un type ne demandant pas d'autorisation d'encadrement (e.g. soirées). Ce rôle peur être attribué par le responsable d'activité.
`+` quelques renames pour plus de clarté:
- Rôle "Bénévole" -> "Organisateur (club)". Peut créer des événements sans lien avec une activité, attribué par l'admin/président
- Badge "Bénévole" -> Bénévole régulier
`+` explication des rôles dans l'interface activité
`+` nettoyage

[FEATURE] Add organizer roles

---

collectives/api/autocomplete_user.py
collectives/static/js/utils/autocomplete.js

Permet d'éviter la sélection de compte expiré, notamment si un utilisateur a un compte en double (par exemple, lors d'un renouvellement avec un numéro de licence et d'email différent)

[FEATURE] Strike expired users in autocomplete

---

collectives/models/registration.py
collectives/routes/event.py
requirements.txt
tests/unit/test_registrations.py

On a toujours ce problème d'inscriptions concurentes: j'aimerais les fix en les détectant et en les enlevant. C'est donc la DB qui fait foi pour savoir quelle inscription il faut conserver.
Je ne dis pas qu'on ne pourrait pas trouver une solution plus élégante, mais elle me parait suffisamment simple.

Fix overbooking

---

collectives/forms/question.py
collectives/models/event/payment.py
collectives/models/question.py
collectives/routes/event.py
collectives/routes/question.py
collectives/templates/payment/edit_prices.html
collectives/templates/question/edit_questions.html
tests/events/test_event.py
tests/test_question.py

- Corrige l'affichage des forms de création de tarifs/questions (incompatibilités avec le nouveau CSS du site)
- Copie les questions lorsqu'on duplique un event
- Ajout d'un form de copie des questions d'un autre event (comme pour les tarifs)

Fix question creation, add ways to copy questions

---

collectives/routes/auth/login.py
collectives/routes/auth/utils.py
collectives/routes/profile.py
collectives/utils/extranet.py
collectives/utils/payline.py
tests/mock/extranet.py
tests/mock/payline.py

- Fix #719 -- extranet auth info may be dynamically changed
- potential fix for #725 -- some extranet related variables may have been erroneously shared query instances
+ add informative message for resynchronizing new license number with existing account

Cleanup and allow live credential changes for SOAP APIs

---

collectives/api/models.py
collectives/static/js/event/eventlist-item.component.js
collectives/templates/index.html

makes `models.js` a proper js module, so that Enums are correctly defined in `config.models`

Fix display of events with non-confirmed status

---

collectives/routes/profile.py
tests/fixtures/client.py
tests/fixtures/user.py
tests/mock/extranet.py
tests/test_extranet.py

+ Add unit tests for resyncing expired user

[FIX] Only logout non-renewed user if they are the one doing the sync

---

collectives/static/js/event/eventlist-filters.component.js
collectives/static/js/event/eventlist-skeleton.component.js

- Hide "clear filter" button, when filter is inactive
- Max height for the multiselect dropdown is 90vh (90% viewport height)
- Fix layout for the event card empty state (when loading)

feat(event-filters): increase multi select viewport & hide clear on empty filter

---

collectives/forms/validators.py
collectives/routes/administration.py
collectives/routes/auth/signup.py
collectives/routes/auth/utils.py
collectives/utils/extranet.py
tests/mock/extranet.py
tests/test_extranet.py

Maintenant que l'api extranet est réparée elle renvoie des auth error lorsqu'on utilise un  numéro d'un autre club. Détecte et affiche un message plus adapté

Nicer error messages when usi a license  number from another club
